//hernad


#define IDR_CEF_CREDITS_JS 0 
#define IDR_CEF_CREDITS_SWIFTSHADER_JPG 0
#define IDR_CEF_CREDITS_HTML 0
#define IDR_CEF_LICENSE_TXT 0
#define IDR_CEF_TRACING_JS 0
#define IDR_CEF_TRACING_HTML 0
#define IDR_CEF_VERSION_HTML 0

#define IDR_CEF_DEVTOOLS_DISCOVERY_PAGE 0

